// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type flowDumpFlowKey struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

// loadFlowDump returns the embedded CollectionSpec for flowDump.
func loadFlowDump() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowDumpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flowDump: %w", err)
	}

	return spec, err
}

// loadFlowDumpObjects loads flowDump and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowDumpObjects
//	*flowDumpPrograms
//	*flowDumpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowDumpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlowDump()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowDumpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowDumpSpecs struct {
	flowDumpProgramSpecs
	flowDumpMapSpecs
	flowDumpVariableSpecs
}

// flowDumpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowDumpProgramSpecs struct {
	OnXmit *ebpf.ProgramSpec `ebpf:"on_xmit"`
}

// flowDumpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowDumpMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	LastSeen *ebpf.MapSpec `ebpf:"last_seen"`
}

// flowDumpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowDumpVariableSpecs struct {
}

// flowDumpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowDumpObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowDumpObjects struct {
	flowDumpPrograms
	flowDumpMaps
	flowDumpVariables
}

func (o *flowDumpObjects) Close() error {
	return _FlowDumpClose(
		&o.flowDumpPrograms,
		&o.flowDumpMaps,
	)
}

// flowDumpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowDumpObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowDumpMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	LastSeen *ebpf.Map `ebpf:"last_seen"`
}

func (m *flowDumpMaps) Close() error {
	return _FlowDumpClose(
		m.Events,
		m.LastSeen,
	)
}

// flowDumpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFlowDumpObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowDumpVariables struct {
}

// flowDumpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowDumpObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowDumpPrograms struct {
	OnXmit *ebpf.Program `ebpf:"on_xmit"`
}

func (p *flowDumpPrograms) Close() error {
	return _FlowDumpClose(
		p.OnXmit,
	)
}

func _FlowDumpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flowdump_x86_bpfel.o
var _FlowDumpBytes []byte
